param(
    [string]$OutputPath=(Join-Path $PSScriptRoot 'native-hierarchy.vsd'),
    [string]$SnapshotPath=(Join-Path $PSScriptRoot 'native-hierarchy.generated.json')
)
# Original neutral shapes only; no source document, template, object or macro.
# Documented native APIs: Master.DrawRectangle, Page.Drop, Selection.Group,
# Styles.Add and Shape.AddSection. Generated bytes require independent reopen.
# https://learn.microsoft.com/en-us/office/vba/api/visio.master.drawrectangle
# https://learn.microsoft.com/en-us/office/vba/api/visio.page.drop
# https://learn.microsoft.com/en-us/office/vba/api/visio.selection.group
# https://learn.microsoft.com/en-us/office/vba/api/visio.styles.add
# https://learn.microsoft.com/en-us/office/vba/api/visio.shape.addsection
$ErrorActionPreference='Stop'
& (Join-Path $PSScriptRoot '../../../scripts/native-visio-broad-snapshot.ps1') -Action generate -OutputPath $SnapshotPath -SavePath $OutputPath
Get-FileHash -LiteralPath $OutputPath -Algorithm SHA256
