export { parseOle2 as parseCompoundFile } from './ole2-parser-read.js';
export * from './ole2-document.js';
export * from './ole2-document-base.js';
export * from './doc-document.js';
export * from './xls-document.js';
export * from './ppt-document.js';
export * from './vsd-document.js';
export { VsdError, type VsdTransform, type VsdGeometry, type VsdGeometryRow, type VsdEllipseGeometry, type VsdGeometrySection } from './vsd-reader.js';
export * from './ole2-parser-types.js';
export * from './ole2-parser-write.js';
export * from './ole2-tree-write.js';
export * from './ole-document-doc-cfb.js';
export * from './ole-document-doc-cp1252.js';
export * from './ole-document-doc-editor.js';
export * from './ole-document-doc-fib.js';
export * from './ole-document-doc-fkp.js';
export * from './ole-document-doc-pieces.js';
export * from './legacy-excel-types.js';
export * from './legacy-excel-cfb.js';
export * from './legacy-excel-biff8.js';
export * from './legacy-excel-biff8-writer.js';
export * from './legacy-office-detect.js';
export * from './legacy-ppt-record-stream.js';
export * from './legacy-ppt-record-types.js';
export * from './legacy-ppt-writer.js';
export * from './ole-summary-properties.js';
export * from './legacy-office-metadata.js';
export * from './legacy-visio-inspect.js';
export * from './legacy-publisher-inspect.js';
export * from './ole2-stream-edit.js';
export * from './ole2-stream-resize.js';
export * from './legacy-ppt-writer.js';
export * from './legacy-excel-workbook.js';
export * from './legacy-ppt-text.js';
export * from './legacy-ppt-text-salvage.js';
export * from './legacy-excel-biff8-edit.js';
export { createXlsNumericCell } from './legacy-excel-create-numeric-cell.js';
export type { XlsCreateNumericCell, XlsCreateNumericCellFailure, XlsCreateNumericCellResult } from './legacy-excel-create-numeric-cell.js';
export * from './legacy-excel-preserved-string-cell.js';
